# Generated by Django 4.0.2 on 2022-10-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_track_trackpoints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackpoints',
            old_name='speed',
            new_name='mph',
        ),
        migrations.AddField(
            model_name='trackpoints',
            name='direction',
            field=models.CharField(default='N', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackpoints',
            name='knts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackpoints',
            name='kph',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
