# Generated by Django 4.0.2 on 2022-10-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_track_display_alter_trackpoint_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackpoint',
            name='direction',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trackpoint',
            name='heading',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackpoint',
            name='knts',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trackpoint',
            name='kph',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trackpoint',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trackpoint',
            name='mph',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trackpoint',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
