# Generated by Django 4.0.2 on 2022-10-11 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_trackpoint_direction_alter_trackpoint_heading_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackpoint',
            old_name='track',
            new_name='track_key',
        ),
    ]
