# Generated by Django 4.0.2 on 2022-10-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_track_trackpoint_track_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackpoint',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
