# Generated by Django 4.0.2 on 2022-10-11 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_trackpoint_lon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackpoint',
            old_name='time',
            new_name='datetime',
        ),
    ]
