# Generated by Django 4.0.2 on 2022-10-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_time_trackpoint_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackpoint',
            name='datetime',
        ),
        migrations.AddField(
            model_name='trackpoint',
            name='time',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
