# Generated by Django 4.0.2 on 2022-10-21 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_trackpoint_datetime_trackpoint_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapmode',
            old_name='dark',
            new_name='value',
        ),
    ]
