# Generated by Django 4.0.2 on 2022-10-21 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_dark_mapmode_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapmode',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
