# Generated by Django 4.0.2 on 2023-02-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_mapmode_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
